name: CI

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: yarn
    - name: Compile
      run: yarn run compile
    - name: Copy assets
      run: yarn run copy-web
    - name: Pack 
      run: yarn run pack
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: vizualisation-0.0.2.vsix
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
